import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#273309",
        "error": "#ba1a1a",
        "primary-container": "#660000",
        "surface-dim": "#dbdad6",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#efeeea",
        "tertiary": "#131d00",
        "secondary-container": "#cfe2f9",
        "surface": "#fbf9f5",
        "inverse-on-surface": "#f2f0ed",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#151f00",
        "primary-fixed-dim": "#ffb4a8",
        "on-background": "#1b1c1a",
        "on-surface": "#1b1c1a",
        "on-secondary-fixed-variant": "#36485b",
        "surface-bright": "#fbf9f5",
        "surface-variant": "#e4e2de",
        "on-tertiary-fixed-variant": "#3e4c20",
        "error-container": "#ffdad6",
        "surface-tint": "#aa3527",
        "surface-container-high": "#eae8e4",
        "secondary-fixed-dim": "#b5c8df",
        "primary": "#3e0000",
        "surface-container-low": "#f5f3ef",
        "on-surface-variant": "#58413e",
        "background": "#fbf9f5",
        "on-secondary-fixed": "#091d2e",
        "on-error": "#ffffff",
        "secondary-fixed": "#d1e4fb",
        "on-primary-fixed-variant": "#891d12",
        "on-primary-container": "#f56b58",
        "inverse-primary": "#ffb4a8",
        "inverse-surface": "#30312e",
        "primary-fixed": "#ffdad4",
        "outline": "#8c716d",
        "tertiary-fixed": "#d9e9ae",
        "surface-container-highest": "#e4e2de",
        "on-tertiary-container": "#8d9d68",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#bdcd94",
        "on-secondary": "#ffffff",
        "secondary": "#4e6073",
        "outline-variant": "#dfbfba",
        "on-primary-fixed": "#410000",
        "on-secondary-container": "#526478"
      },
      fontFamily: {
        "headline": ["Newsreader", "serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
};
export default config;